// Per-client editorial illustrations for the My Style Guide magazine.
//
// One plate at a time is generated by `generateStylePlate({ kind })`, so the
// client can orchestrate Color → Silhouette → Lifestyle sequentially and
// show real "plate N of 3" progress in Bee's voice. Each plate has bounded
// retries (2 retries on transient errors; no retry on 402 credits-exhausted),
// is logged to `style_plate_generations`, and the per-plate status is
// persisted into `style_profiles.illustrations` so the magazine can render
// the per-client image, the live status, or fall back to the static plate.

import { createServerFn } from "@tanstack/react-start";


import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export type PlateKind = "color" | "silhouette" | "lifestyle";
export const PLATE_KINDS: ReadonlyArray<PlateKind> = ["color", "silhouette", "lifestyle"];

export type PlateStatus = "success" | "failed" | "fallback";

export type IllustrationEntry = {
  kind: PlateKind;
  status: PlateStatus;
  path?: string;
  prompt?: string;
  attempts?: number;
  error?: string;
  model?: string;
  duration_ms?: number;
  created_at: string;
};

const WARM_CLIMATES = new Set(["tropical", "arid", "mediterranean"]);

function climateGuidance(climate: string): { wardrobe: string; exclude: string } {
  const c = climate.toLowerCase();
  if (WARM_CLIMATES.has(c) || /tropic|miami|warm|hot|desert/.test(c)) {
    return {
      wardrobe:
        "lightweight, breathable warm-weather pieces — linen, cotton, silk; bare arms or short sleeves; open sandals or low slides; no layering",
      exclude:
        "NO heavy coats, NO wool overcoats, NO scarves, NO gloves, NO knit hats, NO boots, NO winter layers",
    };
  }
  if (/cold|winter|continental/.test(c)) {
    return {
      wardrobe: "cold-weather layering — wool, knits, structured coat, boots",
      exclude: "no bare arms, no sandals, no summer-only pieces",
    };
  }
  return {
    wardrobe: "transitional pieces appropriate to a temperate season",
    exclude: "avoid extreme winter parkas or beach-only resortwear",
  };
}

const COMPOSITION_RULE =
  "Vertical 3:4 portrait. ONE single centered full-length figure that fills the frame head-to-toe with comfortable margin — no cropping at top/bottom/sides, no duplicate or partial second figure, no large empty background void.";

const KIND_BRIEFS: Record<PlateKind, (ctx: PromptContext) => string> = {
  color: (ctx) =>
    `Plate 1 of 3 — COLOR STORY. ${COMPOSITION_RULE} The figure stands in three-quarter view, full-length, painterly editorial portrait. She is in ${ctx.location}, a ${ctx.climate} climate during ${ctx.season}. Outfit: ${ctx.climateWardrobe}, cut in ${ctx.silhouette}, fabrics ${ctx.fabric}. Render the palette as the actual garments, not as swatches. Handwritten script label naming one garment beside (not on) the figure. ${ctx.climateExclude}.\nPalette (in order of importance): ${ctx.paletteLine}.`,
  silhouette: (ctx) =>
    `Plate 2 of 3 — THE BRIEF. ${COMPOSITION_RULE} A DIFFERENT scene from Plate 1: the same figure standing in a relaxed contrapposto with head turned in profile, still full-length and centered, framed against a soft studio backdrop. A DIFFERENT outfit from Plate 1 — still ${ctx.silhouette} cut and ${ctx.fabric} fabrics in the palette, but a separate look (e.g. a dress where Plate 1 was separates, or vice versa). Setting reads as her ${ctx.location} during ${ctx.season}. Small handwritten note "${ctx.northStarShort}" floating beside her. ${ctx.climateWardrobe}. ${ctx.climateExclude}.\nPalette: ${ctx.paletteLine}.`,
  lifestyle: (ctx) =>
    `Plate 3 of 3 — ECHOES. ${COMPOSITION_RULE} A DIFFERENT scene again: the figure walking or stepping forward in mid-motion, still full-length and centered head-to-toe, looser brushwork than Plates 1 and 2. A THIRD distinct outfit — not the standing look from Plate 1 and not the second look from Plate 2 — still ${ctx.silhouette} cut and ${ctx.fabric} in the palette. Background suggested loosely as a ${ctx.dominantContext} setting (${ctx.location}, ${ctx.climate}, ${ctx.season}), never literal and never a wide empty void. ${ctx.climateWardrobe}. ${ctx.climateExclude}.\nLifestyle mix: ${ctx.lifestyleLine}. Palette: ${ctx.paletteLine}.\nVARY pose and outfit from the other two plates — no two plates should look alike.`,
};

type PromptContext = {
  paletteLine: string;
  silhouette: string;
  fabric: string;
  lifestyleLine: string;
  dominantContext: string;
  northStarShort: string;
  location: string;
  climate: string;
  season: string;
  climateWardrobe: string;
  climateExclude: string;
};

const MODEL_NAME = "google/gemini-3.1-flash-image-preview";
const MAX_ATTEMPTS = 3; // 1 initial + 2 retries

function currentSeason(climate: string): string {
  const m = new Date().getUTCMonth(); // 0=Jan
  const c = climate.toLowerCase();
  if (WARM_CLIMATES.has(c) || /tropic|miami|warm|hot|desert/.test(c)) {
    // tropical/warm: wet vs dry rather than 4 seasons
    return m >= 4 && m <= 9 ? "the warm, humid season" : "the dry, breezy season";
  }
  // Northern-hemisphere default
  if (m <= 1 || m === 11) return "winter";
  if (m <= 4) return "spring";
  if (m <= 7) return "summer";
  return "autumn";
}

// Real loader — typed against the auth context's supabase client.
async function loadPromptContext(
  supabase: Awaited<ReturnType<typeof getAuthSupabase>>,
  userId: string,
): Promise<{ ctx: PromptContext } | { error: string }> {
  const [{ data: sp }, { data: profile }, { data: onboarding }] = await Promise.all([
    supabase
      .from("style_profiles")
      .select("color_palette, pillar_weights, lifestyle_mix, north_star")
      .eq("user_id", userId)
      .maybeSingle(),
    supabase.from("profiles").select("location, climate").eq("id", userId).maybeSingle(),
    supabase.from("bee_onboarding_responses").select("question_id, choice").eq("user_id", userId),
  ]);

  const palette = Array.isArray(sp?.color_palette)
    ? (sp!.color_palette as Array<{ name?: string; hex?: string; role?: string }>)
    : [];
  if (palette.length === 0) {
    return { error: "no palette yet — talk to Bee first" };
  }

  const byQ = new Map<string, string>();
  for (const o of onboarding ?? []) {
    if (o.question_id && o.choice) byQ.set(o.question_id as string, o.choice as string);
  }

  const lifestyleMix = (sp?.lifestyle_mix ?? {}) as Record<string, number>;
  const dominantContext =
    Object.entries(lifestyleMix).sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0))[0]?.[0] ??
    byQ.get("q8_lifestyle") ??
    "everyday life";

  const location = (profile?.location as string | null)?.trim() || "her city";
  const climate = (profile?.climate as string | null)?.trim() || "temperate";
  const season = currentSeason(climate);
  const guidance = climateGuidance(climate);

  return {
    ctx: {
      paletteLine: palette
        .slice(0, 6)
        .map(
          (p) => `${p.name ?? "tone"}${p.hex ? ` (${p.hex})` : ""}${p.role ? ` — ${p.role}` : ""}`,
        )
        .join("; "),
      silhouette: byQ.get("q4_silhouette") ?? "easy, draped",
      fabric: byQ.get("q6_fabric_preference") ?? "soft naturals",
      lifestyleLine:
        Object.entries(lifestyleMix)
          .sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0))
          .slice(0, 3)
          .map(([k, v]) => `${k} ${v}%`)
          .join(", ") ||
        (byQ.get("q8_lifestyle") ?? "mixed"),
      dominantContext,
      northStarShort: ((sp?.north_star as string | null) ?? "show up as me").slice(0, 60),
      location,
      climate,
      season,
      climateWardrobe: guidance.wardrobe,
      climateExclude: guidance.exclude,
    },
  };
}

// Helper type for `loadPromptContext` — never used at runtime.
async function getAuthSupabase() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin;
}

type GenAttempt =
  | { ok: true; bytes: Uint8Array; durationMs: number }
  | { ok: false; status: number; error: string; durationMs: number };

function responseSnippet(text: string): string {
  return text.replace(/\s+/g, " ").trim().slice(0, 220);
}

async function callImageRoute(apiKey: string, prompt: string): Promise<GenAttempt> {
  const start = Date.now();
  try {
    const { generateIllustrationBytes } = await import("@/lib/generate-illustration.server");
    const result = await generateIllustrationBytes({
      prompt,
      apiKey,
      logPrefix: "[generate-style-plate]",
    });
    return { ok: true, bytes: result.bytes, durationMs: Date.now() - start };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      ok: false,
      status: 502,
      error: responseSnippet(message),
      durationMs: Date.now() - start,
    };
  }
}

const isRetryable = (status: number) => status !== 402 && status !== 401 && status !== 403;

async function runOnePlate(params: {
  supabase: Awaited<ReturnType<typeof getAuthSupabase>>;
  userId: string;
  kind: PlateKind;
  ctx: PromptContext;
}): Promise<IllustrationEntry> {
  const { supabase, userId, kind, ctx } = params;
  const prompt = KIND_BRIEFS[kind](ctx);
  const apiKey = process.env.ONIXUS_AI_API_KEY ?? "";
  const startedAt = new Date().toISOString();

  let attempts = 0;
  let lastError = "unknown error";
  let lastStatus = 0;
  let totalDuration = 0;
  let bytes: Uint8Array | null = null;

  while (attempts < MAX_ATTEMPTS) {
    attempts += 1;
    const r = await callImageRoute(apiKey, prompt);
    totalDuration += r.durationMs;
    if (r.ok) {
      bytes = r.bytes;
      break;
    }
    lastError = r.error;
    lastStatus = r.status;
    // Don't burn credits on 402 / auth errors.
    if (!isRetryable(r.status) || attempts >= MAX_ATTEMPTS) break;
    // Short backoff: 600ms, 1500ms.
    await new Promise((res) => setTimeout(res, attempts === 1 ? 600 : 1500));
  }

  // Log every attempt cluster as one row.
  const baseLog = {
    user_id: userId,
    kind,
    model: MODEL_NAME,
    prompt,
    attempts,
    duration_ms: totalDuration,
    created_at: startedAt,
  };

  if (!bytes) {
    const failedEntry: IllustrationEntry = {
      kind,
      status: lastStatus === 402 ? "fallback" : "failed",
      attempts,
      error: lastError,
      prompt,
      model: MODEL_NAME,
      duration_ms: totalDuration,
      created_at: startedAt,
    };
    await supabase.from("style_plate_generations").insert({
      ...baseLog,
      status: failedEntry.status,
      error: lastError,
    });
    return failedEntry;
  }

  const path = `${userId}/plate-${kind}.png`;
  const { error: uploadErr } = await supabase.storage
    .from("style-illustrations")
    .upload(path, bytes, { contentType: "image/png", upsert: true });
  if (uploadErr) {
    const entry: IllustrationEntry = {
      kind,
      status: "failed",
      attempts,
      error: `upload ${uploadErr.message}`,
      prompt,
      model: MODEL_NAME,
      duration_ms: totalDuration,
      created_at: startedAt,
    };
    await supabase.from("style_plate_generations").insert({
      ...baseLog,
      status: "failed",
      error: entry.error,
    });
    return entry;
  }

  const entry: IllustrationEntry = {
    kind,
    status: "success",
    path,
    prompt,
    attempts,
    model: MODEL_NAME,
    duration_ms: totalDuration,
    created_at: startedAt,
  };
  await supabase.from("style_plate_generations").insert({
    ...baseLog,
    status: "success",
  });
  return entry;
}

async function mergeAndPersist(
  supabase: Awaited<ReturnType<typeof getAuthSupabase>>,
  userId: string,
  entry: IllustrationEntry,
): Promise<void> {
  const { data: existing } = await supabase
    .from("style_profiles")
    .select("illustrations")
    .eq("user_id", userId)
    .maybeSingle();
  const prev = Array.isArray(existing?.illustrations)
    ? (existing!.illustrations as IllustrationEntry[])
    : [];
  const next = [...prev.filter((p) => p?.kind !== entry.kind), entry];
  await supabase
    .from("style_profiles")
    .upsert(
      { user_id: userId, illustrations: next as unknown as never },
      { onConflict: "user_id" },
    );
}

// Generate (or regenerate) a single plate. The client calls this once per
// kind so it can show "plate N of 3" progress between calls.
export const generateStylePlate = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: { kind: PlateKind }) => {
    if (!d?.kind || !PLATE_KINDS.includes(d.kind)) throw new Error("Invalid plate kind");
    return d;
  })
  .handler(
    async ({
      data,
      context,
    }): Promise<{ ok: boolean; entry: IllustrationEntry } | { ok: false; error: string }> => {
      const { supabase, userId } = context;
      if (!process.env.ONIXUS_AI_API_KEY) return { ok: false, error: "Missing ONIXUS_AI_API_KEY" };
      const ctxResult = await loadPromptContext(supabase as never, userId);
      if ("error" in ctxResult) return { ok: false, error: ctxResult.error };
      const entry = await runOnePlate({
        supabase: supabase as never,
        userId,
        kind: data.kind,
        ctx: ctxResult.ctx,
      });
      await mergeAndPersist(supabase as never, userId, entry);
      return { ok: entry.status === "success", entry };
    },
  );

// Return the list of plate kinds that are NOT currently in `success` state.
// Used by the "regenerate missing" action.
export const getMissingStylePlates = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }): Promise<{ missing: PlateKind[] }> => {
    const { data: sp } = await context.supabase
      .from("style_profiles")
      .select("illustrations")
      .eq("user_id", context.userId)
      .maybeSingle();
    const entries = Array.isArray(sp?.illustrations)
      ? (sp!.illustrations as IllustrationEntry[])
      : [];
    const succeededByKind = new Map<PlateKind, boolean>();
    for (const e of entries) {
      if (e?.kind && e.status === "success") succeededByKind.set(e.kind, true);
    }
    return { missing: PLATE_KINDS.filter((k) => !succeededByKind.get(k)) };
  });

// Convenience: server-side sequential generation of every plate. Kept for
// scripts/cron — the UI uses generateStylePlate per kind for progress.
export const generateMyStyleIllustrations = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(
    async ({
      context,
    }): Promise<{
      ok: boolean;
      generated: number;
      skipped?: string;
      error?: string;
    }> => {
      const { supabase, userId } = context;
      if (!process.env.ONIXUS_AI_API_KEY)
        return { ok: false, generated: 0, error: "Missing ONIXUS_AI_API_KEY" };
      const ctxResult = await loadPromptContext(supabase as never, userId);
      if ("error" in ctxResult) return { ok: false, generated: 0, skipped: ctxResult.error };
      let okCount = 0;
      const errors: string[] = [];
      for (const kind of PLATE_KINDS) {
        const entry = await runOnePlate({
          supabase: supabase as never,
          userId,
          kind,
          ctx: ctxResult.ctx,
        });
        await mergeAndPersist(supabase as never, userId, entry);
        if (entry.status === "success") okCount += 1;
        else errors.push(`${kind}: ${entry.error ?? entry.status}`);
      }
      return {
        ok: okCount > 0,
        generated: okCount,
        ...(errors.length ? { error: errors.join(" · ") } : {}),
      };
    },
  );

// Suppress "unused" warnings for the type-only helper.
