import { createFileRoute, Link } from "@tanstack/react-router";
import { Footer } from "@/components/Footer";

export const Route = createFileRoute("/trust")({
  head: () => ({
    meta: [
      { title: "Trust & Privacy — LiveAskew" },
      {
        name: "description",
        content:
          "How LiveAskew handles your account, your styling data, and the controls that protect your privacy.",
      },
      { property: "og:title", content: "Trust & Privacy — LiveAskew" },
      {
        property: "og:description",
        content:
          "Plain-English overview of how LiveAskew handles accounts, data, and privacy controls.",
      },
    ],
  }),
  component: TrustPage,
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-ink/10 pt-10">
      <h2 className="font-display text-2xl text-ink md:text-3xl">{title}</h2>
      <div className="mt-4 space-y-3 font-serif text-[1.05rem] leading-relaxed text-ink/80">
        {children}
      </div>
    </section>
  );
}

function TrustPage() {
  return (
    <div className="min-h-screen bg-cream text-ink">
      <header className="mx-auto flex max-w-[1100px] items-center justify-between px-6 pt-10 md:px-10">
        <Link to="/" className="font-display text-2xl tracking-tight">
          Live<em className="text-gold-deep">Askew</em>
        </Link>
        <Link
          to="/"
          className="text-[0.65rem] tracking-[0.25em] uppercase text-ink/55 hover:text-gold-deep"
        >
          ← Home
        </Link>
      </header>

      <main className="mx-auto max-w-[820px] px-6 py-16 md:px-10 md:py-24">
        <p className="text-[0.65rem] tracking-[0.3em] uppercase text-ink/50">Trust & Privacy</p>
        <h1 className="mt-3 font-display text-4xl leading-tight md:text-5xl">
          How we handle your account and your styling data
        </h1>
        <p className="mt-5 font-serif text-lg italic text-ink/70">
          This page is maintained by the LiveAskew team to answer common questions about security
          and privacy. It describes the controls that are enabled in the app today — it is not an
          independent certification or audit.
        </p>

        <div className="mt-12 space-y-12">
          <Section title="Accounts & authentication">
            <p>
              Sign-in is handled through our managed auth backend. We support email & password and
              Google sign-in. Sessions are stored in your browser and can be revoked at any time by
              signing out.
            </p>
            <p>
              Only you can read or change your style profile, wardrobe, looks, calendar, and chat
              history. These tables enforce row-level access rules so every read and write is
              scoped to your own user id.
            </p>
          </Section>

          <Section title="What we collect">
            <p>
              We store the information you provide while using the app: your onboarding answers,
              chat with Bee, generated looks and illustrations, wardrobe items you add, any selfies
              you upload, and basic profile fields (email, display name).
            </p>
            <p>
              We do not sell your data. We do not use your styling content to train third-party
              models outside the providers we call to generate your guide.
            </p>
          </Section>

          <Section title="AI providers & subprocessors">
            <p>
              Styling responses and illustrations are generated by AI models routed through our
              gateway. Payments are processed by Stripe. Transactional email is sent through our
              managed email infrastructure. We share with these providers only the data needed to
              complete the request.
            </p>
          </Section>

          <Section title="Storage & images">
            <p>
              Wardrobe photos and selfies live in private storage buckets — only you can list or
              read your own files. Generated style illustrations live in a bucket that serves
              direct image URLs (so your guide loads quickly) but the bucket cannot be browsed.
            </p>
          </Section>

          <Section title="Payments & subscriptions">
            <p>
              Card details are entered directly with Stripe — LiveAskew never sees or stores your
              card number. We only keep the subscription status and identifiers we need to keep
              your account in good standing.
            </p>
          </Section>

          <Section title="Deletion & data requests">
            <p>
              You can delete content you create inside the app. If you'd like your entire account
              and all associated styling data removed, email us and we'll take care of it.
            </p>
          </Section>

          <Section title="Security contact">
            <p>
              Found something that looks like a security issue? Please email us before disclosing
              publicly so we can investigate and fix it. We appreciate responsible reports.
            </p>
          </Section>
        </div>

        <p className="mt-16 text-[0.65rem] tracking-[0.25em] uppercase text-ink/45">
          Last reviewed June 2026 · Maintained by the LiveAskew team
        </p>
      </main>

      <Footer />
    </div>
  );
}
