/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as ApiGenerateIllustrationRouteImport } from './routes/api/generate-illustration'
import { Route as ApiWardrobeAnalyzeRouteImport } from './routes/api/wardrobe/analyze'
import { Route as ApiPushRegisterRouteImport } from './routes/api/push/register'
import { Route as ApiPushRecommendRouteImport } from './routes/api/push/recommend'
import { Route as ApiPublicVerifyRouteImport } from './routes/api/public/verify'
import { Route as ApiCronPushRouteImport } from './routes/api/cron/push'
import { Route as ApiBeeStreamRouteImport } from './routes/api/bee/stream'
import { Route as ApiBeeMagazineStreamRouteImport } from './routes/api/bee/magazine-stream'
import { Route as ApiBeeAppRouteImport } from './routes/api/bee/app'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBeeGuestRouteImport } from './routes/api/public/bee/guest'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateIllustrationRoute = ApiGenerateIllustrationRouteImport.update({
  id: '/api/generate-illustration',
  path: '/api/generate-illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWardrobeAnalyzeRoute = ApiWardrobeAnalyzeRouteImport.update({
  id: '/api/wardrobe/analyze',
  path: '/api/wardrobe/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRegisterRoute = ApiPushRegisterRouteImport.update({
  id: '/api/push/register',
  path: '/api/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRecommendRoute = ApiPushRecommendRouteImport.update({
  id: '/api/push/recommend',
  path: '/api/push/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyRoute = ApiPublicVerifyRouteImport.update({
  id: '/api/public/verify',
  path: '/api/public/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPushRoute = ApiCronPushRouteImport.update({
  id: '/api/cron/push',
  path: '/api/cron/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeStreamRoute = ApiBeeStreamRouteImport.update({
  id: '/api/bee/stream',
  path: '/api/bee/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeMagazineStreamRoute = ApiBeeMagazineStreamRouteImport.update({
  id: '/api/bee/magazine-stream',
  path: '/api/bee/magazine-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeAppRoute = ApiBeeAppRouteImport.update({
  id: '/api/bee/app',
  path: '/api/bee/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBeeGuestRoute = ApiPublicBeeGuestRouteImport.update({
  id: '/api/public/bee/guest',
  path: '/api/public/bee/guest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/api/tryon': typeof ApiTryonRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/api/tryon': typeof ApiTryonRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/api/tryon': typeof ApiTryonRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/api/generate-illustration'
    | '/api/tryon'
    | '/api/bee/app'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/api/cron/push'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/api/generate-illustration'
    | '/api/tryon'
    | '/api/bee/app'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/api/cron/push'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/api/generate-illustration'
    | '/api/tryon'
    | '/api/bee/app'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/api/cron/push'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiGenerateIllustrationRoute: typeof ApiGenerateIllustrationRoute
  ApiTryonRoute: typeof ApiTryonRoute
  ApiBeeAppRoute: typeof ApiBeeAppRoute
  ApiBeeMagazineStreamRoute: typeof ApiBeeMagazineStreamRoute
  ApiBeeStreamRoute: typeof ApiBeeStreamRoute
  ApiCronPushRoute: typeof ApiCronPushRoute
  ApiPublicVerifyRoute: typeof ApiPublicVerifyRoute
  ApiPushRecommendRoute: typeof ApiPushRecommendRoute
  ApiPushRegisterRoute: typeof ApiPushRegisterRoute
  ApiWardrobeAnalyzeRoute: typeof ApiWardrobeAnalyzeRoute
  ApiPublicBeeGuestRoute: typeof ApiPublicBeeGuestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-illustration': {
      id: '/api/generate-illustration'
      path: '/api/generate-illustration'
      fullPath: '/api/generate-illustration'
      preLoaderRoute: typeof ApiGenerateIllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wardrobe/analyze': {
      id: '/api/wardrobe/analyze'
      path: '/api/wardrobe/analyze'
      fullPath: '/api/wardrobe/analyze'
      preLoaderRoute: typeof ApiWardrobeAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/register': {
      id: '/api/push/register'
      path: '/api/push/register'
      fullPath: '/api/push/register'
      preLoaderRoute: typeof ApiPushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/recommend': {
      id: '/api/push/recommend'
      path: '/api/push/recommend'
      fullPath: '/api/push/recommend'
      preLoaderRoute: typeof ApiPushRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify': {
      id: '/api/public/verify'
      path: '/api/public/verify'
      fullPath: '/api/public/verify'
      preLoaderRoute: typeof ApiPublicVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/push': {
      id: '/api/cron/push'
      path: '/api/cron/push'
      fullPath: '/api/cron/push'
      preLoaderRoute: typeof ApiCronPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/stream': {
      id: '/api/bee/stream'
      path: '/api/bee/stream'
      fullPath: '/api/bee/stream'
      preLoaderRoute: typeof ApiBeeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/magazine-stream': {
      id: '/api/bee/magazine-stream'
      path: '/api/bee/magazine-stream'
      fullPath: '/api/bee/magazine-stream'
      preLoaderRoute: typeof ApiBeeMagazineStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/app': {
      id: '/api/bee/app'
      path: '/api/bee/app'
      fullPath: '/api/bee/app'
      preLoaderRoute: typeof ApiBeeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bee/guest': {
      id: '/api/public/bee/guest'
      path: '/api/public/bee/guest'
      fullPath: '/api/public/bee/guest'
      preLoaderRoute: typeof ApiPublicBeeGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ApiGenerateIllustrationRoute: ApiGenerateIllustrationRoute,
  ApiTryonRoute: ApiTryonRoute,
  ApiBeeAppRoute: ApiBeeAppRoute,
  ApiBeeMagazineStreamRoute: ApiBeeMagazineStreamRoute,
  ApiBeeStreamRoute: ApiBeeStreamRoute,
  ApiCronPushRoute: ApiCronPushRoute,
  ApiPublicVerifyRoute: ApiPublicVerifyRoute,
  ApiPushRecommendRoute: ApiPushRecommendRoute,
  ApiPushRegisterRoute: ApiPushRegisterRoute,
  ApiWardrobeAnalyzeRoute: ApiWardrobeAnalyzeRoute,
  ApiPublicBeeGuestRoute: ApiPublicBeeGuestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
