/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as DnsMigrationRouteImport } from './routes/dns-migration'
import { Route as BiancaRouteImport } from './routes/bianca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StyleGuideIndexRouteImport } from './routes/style-guide.index'
import { Route as StyleGuideVoiceRouteImport } from './routes/style-guide.voice'
import { Route as StyleGuideTypographyRouteImport } from './routes/style-guide.typography'
import { Route as StyleGuidePhotographyRouteImport } from './routes/style-guide.photography'
import { Route as StyleGuideLogoRouteImport } from './routes/style-guide.logo'
import { Route as StyleGuideIllustrationRouteImport } from './routes/style-guide.illustration'
import { Route as StyleGuideComponentsRouteImport } from './routes/style-guide.components'
import { Route as StyleGuideColorRouteImport } from './routes/style-guide.color'
import { Route as ApiGenerateIllustrationRouteImport } from './routes/api/generate-illustration'
import { Route as AuthenticatedWardrobeRouteImport } from './routes/_authenticated/wardrobe'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyStyleGuideRouteImport } from './routes/_authenticated/my-style-guide'
import { Route as AuthenticatedMagazineRouteImport } from './routes/_authenticated/magazine'
import { Route as AuthenticatedHouseholdRouteImport } from './routes/_authenticated/household'
import { Route as AuthenticatedDnsCheckRouteImport } from './routes/_authenticated/dns-check'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as ShareStyleGuideTokenRouteImport } from './routes/share/style-guide.$token'
import { Route as ApiBeeStreamRouteImport } from './routes/api/bee/stream'
import { Route as ApiBeeMagazineStreamRouteImport } from './routes/api/bee/magazine-stream'
import { Route as AuthenticatedCheckoutTierRouteImport } from './routes/_authenticated/checkout.$tier'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBeeGuestRouteImport } from './routes/api/public/bee/guest'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsMigrationRoute = DnsMigrationRouteImport.update({
  id: '/dns-migration',
  path: '/dns-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const BiancaRoute = BiancaRouteImport.update({
  id: '/bianca',
  path: '/bianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideIndexRoute = StyleGuideIndexRouteImport.update({
  id: '/style-guide/',
  path: '/style-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideVoiceRoute = StyleGuideVoiceRouteImport.update({
  id: '/style-guide/voice',
  path: '/style-guide/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideTypographyRoute = StyleGuideTypographyRouteImport.update({
  id: '/style-guide/typography',
  path: '/style-guide/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuidePhotographyRoute = StyleGuidePhotographyRouteImport.update({
  id: '/style-guide/photography',
  path: '/style-guide/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideLogoRoute = StyleGuideLogoRouteImport.update({
  id: '/style-guide/logo',
  path: '/style-guide/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideIllustrationRoute = StyleGuideIllustrationRouteImport.update({
  id: '/style-guide/illustration',
  path: '/style-guide/illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideComponentsRoute = StyleGuideComponentsRouteImport.update({
  id: '/style-guide/components',
  path: '/style-guide/components',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideColorRoute = StyleGuideColorRouteImport.update({
  id: '/style-guide/color',
  path: '/style-guide/color',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateIllustrationRoute = ApiGenerateIllustrationRouteImport.update({
  id: '/api/generate-illustration',
  path: '/api/generate-illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWardrobeRoute = AuthenticatedWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyStyleGuideRoute =
  AuthenticatedMyStyleGuideRouteImport.update({
    id: '/my-style-guide',
    path: '/my-style-guide',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMagazineRoute = AuthenticatedMagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHouseholdRoute = AuthenticatedHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnsCheckRoute = AuthenticatedDnsCheckRouteImport.update({
  id: '/dns-check',
  path: '/dns-check',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareStyleGuideTokenRoute = ShareStyleGuideTokenRouteImport.update({
  id: '/share/style-guide/$token',
  path: '/share/style-guide/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeStreamRoute = ApiBeeStreamRouteImport.update({
  id: '/api/bee/stream',
  path: '/api/bee/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeMagazineStreamRoute = ApiBeeMagazineStreamRouteImport.update({
  id: '/api/bee/magazine-stream',
  path: '/api/bee/magazine-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutTierRoute =
  AuthenticatedCheckoutTierRouteImport.update({
    id: '/checkout/$tier',
    path: '/checkout/$tier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBeeGuestRoute = ApiPublicBeeGuestRouteImport.update({
  id: '/api/public/bee/guest',
  path: '/api/public/bee/guest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bianca': typeof BiancaRoute
  '/dns-migration': typeof DnsMigrationRoute
  '/inquiry': typeof InquiryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/trust': typeof TrustRoute
  '/verify-email': typeof VerifyEmailRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dns-check': typeof AuthenticatedDnsCheckRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/magazine': typeof AuthenticatedMagazineRoute
  '/my-style-guide': typeof AuthenticatedMyStyleGuideRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/style-guide/color': typeof StyleGuideColorRoute
  '/style-guide/components': typeof StyleGuideComponentsRoute
  '/style-guide/illustration': typeof StyleGuideIllustrationRoute
  '/style-guide/logo': typeof StyleGuideLogoRoute
  '/style-guide/photography': typeof StyleGuidePhotographyRoute
  '/style-guide/typography': typeof StyleGuideTypographyRoute
  '/style-guide/voice': typeof StyleGuideVoiceRoute
  '/style-guide/': typeof StyleGuideIndexRoute
  '/checkout/$tier': typeof AuthenticatedCheckoutTierRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/share/style-guide/$token': typeof ShareStyleGuideTokenRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bianca': typeof BiancaRoute
  '/dns-migration': typeof DnsMigrationRoute
  '/inquiry': typeof InquiryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/trust': typeof TrustRoute
  '/verify-email': typeof VerifyEmailRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dns-check': typeof AuthenticatedDnsCheckRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/magazine': typeof AuthenticatedMagazineRoute
  '/my-style-guide': typeof AuthenticatedMyStyleGuideRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/style-guide/color': typeof StyleGuideColorRoute
  '/style-guide/components': typeof StyleGuideComponentsRoute
  '/style-guide/illustration': typeof StyleGuideIllustrationRoute
  '/style-guide/logo': typeof StyleGuideLogoRoute
  '/style-guide/photography': typeof StyleGuidePhotographyRoute
  '/style-guide/typography': typeof StyleGuideTypographyRoute
  '/style-guide/voice': typeof StyleGuideVoiceRoute
  '/style-guide': typeof StyleGuideIndexRoute
  '/checkout/$tier': typeof AuthenticatedCheckoutTierRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/share/style-guide/$token': typeof ShareStyleGuideTokenRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bianca': typeof BiancaRoute
  '/dns-migration': typeof DnsMigrationRoute
  '/inquiry': typeof InquiryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/trust': typeof TrustRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dns-check': typeof AuthenticatedDnsCheckRoute
  '/_authenticated/household': typeof AuthenticatedHouseholdRoute
  '/_authenticated/magazine': typeof AuthenticatedMagazineRoute
  '/_authenticated/my-style-guide': typeof AuthenticatedMyStyleGuideRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/generate-illustration': typeof ApiGenerateIllustrationRoute
  '/style-guide/color': typeof StyleGuideColorRoute
  '/style-guide/components': typeof StyleGuideComponentsRoute
  '/style-guide/illustration': typeof StyleGuideIllustrationRoute
  '/style-guide/logo': typeof StyleGuideLogoRoute
  '/style-guide/photography': typeof StyleGuidePhotographyRoute
  '/style-guide/typography': typeof StyleGuideTypographyRoute
  '/style-guide/voice': typeof StyleGuideVoiceRoute
  '/style-guide/': typeof StyleGuideIndexRoute
  '/_authenticated/checkout/$tier': typeof AuthenticatedCheckoutTierRoute
  '/api/bee/magazine-stream': typeof ApiBeeMagazineStreamRoute
  '/api/bee/stream': typeof ApiBeeStreamRoute
  '/share/style-guide/$token': typeof ShareStyleGuideTokenRoute
  '/api/public/bee/guest': typeof ApiPublicBeeGuestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bianca'
    | '/dns-migration'
    | '/inquiry'
    | '/onboarding'
    | '/pricing'
    | '/trust'
    | '/verify-email'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/dns-check'
    | '/household'
    | '/magazine'
    | '/my-style-guide'
    | '/profile'
    | '/wardrobe'
    | '/api/generate-illustration'
    | '/style-guide/color'
    | '/style-guide/components'
    | '/style-guide/illustration'
    | '/style-guide/logo'
    | '/style-guide/photography'
    | '/style-guide/typography'
    | '/style-guide/voice'
    | '/style-guide/'
    | '/checkout/$tier'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/share/style-guide/$token'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bianca'
    | '/dns-migration'
    | '/inquiry'
    | '/onboarding'
    | '/pricing'
    | '/trust'
    | '/verify-email'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/dns-check'
    | '/household'
    | '/magazine'
    | '/my-style-guide'
    | '/profile'
    | '/wardrobe'
    | '/api/generate-illustration'
    | '/style-guide/color'
    | '/style-guide/components'
    | '/style-guide/illustration'
    | '/style-guide/logo'
    | '/style-guide/photography'
    | '/style-guide/typography'
    | '/style-guide/voice'
    | '/style-guide'
    | '/checkout/$tier'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/share/style-guide/$token'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bianca'
    | '/dns-migration'
    | '/inquiry'
    | '/onboarding'
    | '/pricing'
    | '/trust'
    | '/verify-email'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/dns-check'
    | '/_authenticated/household'
    | '/_authenticated/magazine'
    | '/_authenticated/my-style-guide'
    | '/_authenticated/profile'
    | '/_authenticated/wardrobe'
    | '/api/generate-illustration'
    | '/style-guide/color'
    | '/style-guide/components'
    | '/style-guide/illustration'
    | '/style-guide/logo'
    | '/style-guide/photography'
    | '/style-guide/typography'
    | '/style-guide/voice'
    | '/style-guide/'
    | '/_authenticated/checkout/$tier'
    | '/api/bee/magazine-stream'
    | '/api/bee/stream'
    | '/share/style-guide/$token'
    | '/api/public/bee/guest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BiancaRoute: typeof BiancaRoute
  DnsMigrationRoute: typeof DnsMigrationRoute
  InquiryRoute: typeof InquiryRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  TrustRoute: typeof TrustRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiGenerateIllustrationRoute: typeof ApiGenerateIllustrationRoute
  StyleGuideColorRoute: typeof StyleGuideColorRoute
  StyleGuideComponentsRoute: typeof StyleGuideComponentsRoute
  StyleGuideIllustrationRoute: typeof StyleGuideIllustrationRoute
  StyleGuideLogoRoute: typeof StyleGuideLogoRoute
  StyleGuidePhotographyRoute: typeof StyleGuidePhotographyRoute
  StyleGuideTypographyRoute: typeof StyleGuideTypographyRoute
  StyleGuideVoiceRoute: typeof StyleGuideVoiceRoute
  StyleGuideIndexRoute: typeof StyleGuideIndexRoute
  ApiBeeMagazineStreamRoute: typeof ApiBeeMagazineStreamRoute
  ApiBeeStreamRoute: typeof ApiBeeStreamRoute
  ShareStyleGuideTokenRoute: typeof ShareStyleGuideTokenRoute
  ApiPublicBeeGuestRoute: typeof ApiPublicBeeGuestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-migration': {
      id: '/dns-migration'
      path: '/dns-migration'
      fullPath: '/dns-migration'
      preLoaderRoute: typeof DnsMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bianca': {
      id: '/bianca'
      path: '/bianca'
      fullPath: '/bianca'
      preLoaderRoute: typeof BiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/': {
      id: '/style-guide/'
      path: '/style-guide'
      fullPath: '/style-guide/'
      preLoaderRoute: typeof StyleGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/voice': {
      id: '/style-guide/voice'
      path: '/style-guide/voice'
      fullPath: '/style-guide/voice'
      preLoaderRoute: typeof StyleGuideVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/typography': {
      id: '/style-guide/typography'
      path: '/style-guide/typography'
      fullPath: '/style-guide/typography'
      preLoaderRoute: typeof StyleGuideTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/photography': {
      id: '/style-guide/photography'
      path: '/style-guide/photography'
      fullPath: '/style-guide/photography'
      preLoaderRoute: typeof StyleGuidePhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/logo': {
      id: '/style-guide/logo'
      path: '/style-guide/logo'
      fullPath: '/style-guide/logo'
      preLoaderRoute: typeof StyleGuideLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/illustration': {
      id: '/style-guide/illustration'
      path: '/style-guide/illustration'
      fullPath: '/style-guide/illustration'
      preLoaderRoute: typeof StyleGuideIllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/components': {
      id: '/style-guide/components'
      path: '/style-guide/components'
      fullPath: '/style-guide/components'
      preLoaderRoute: typeof StyleGuideComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide/color': {
      id: '/style-guide/color'
      path: '/style-guide/color'
      fullPath: '/style-guide/color'
      preLoaderRoute: typeof StyleGuideColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-illustration': {
      id: '/api/generate-illustration'
      path: '/api/generate-illustration'
      fullPath: '/api/generate-illustration'
      preLoaderRoute: typeof ApiGenerateIllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wardrobe': {
      id: '/_authenticated/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof AuthenticatedWardrobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-style-guide': {
      id: '/_authenticated/my-style-guide'
      path: '/my-style-guide'
      fullPath: '/my-style-guide'
      preLoaderRoute: typeof AuthenticatedMyStyleGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magazine': {
      id: '/_authenticated/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof AuthenticatedMagazineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/household': {
      id: '/_authenticated/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedHouseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-check': {
      id: '/_authenticated/dns-check'
      path: '/dns-check'
      fullPath: '/dns-check'
      preLoaderRoute: typeof AuthenticatedDnsCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/style-guide/$token': {
      id: '/share/style-guide/$token'
      path: '/share/style-guide/$token'
      fullPath: '/share/style-guide/$token'
      preLoaderRoute: typeof ShareStyleGuideTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/stream': {
      id: '/api/bee/stream'
      path: '/api/bee/stream'
      fullPath: '/api/bee/stream'
      preLoaderRoute: typeof ApiBeeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/magazine-stream': {
      id: '/api/bee/magazine-stream'
      path: '/api/bee/magazine-stream'
      fullPath: '/api/bee/magazine-stream'
      preLoaderRoute: typeof ApiBeeMagazineStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/$tier': {
      id: '/_authenticated/checkout/$tier'
      path: '/checkout/$tier'
      fullPath: '/checkout/$tier'
      preLoaderRoute: typeof AuthenticatedCheckoutTierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bee/guest': {
      id: '/api/public/bee/guest'
      path: '/api/public/bee/guest'
      fullPath: '/api/public/bee/guest'
      preLoaderRoute: typeof ApiPublicBeeGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDnsCheckRoute: typeof AuthenticatedDnsCheckRoute
  AuthenticatedHouseholdRoute: typeof AuthenticatedHouseholdRoute
  AuthenticatedMagazineRoute: typeof AuthenticatedMagazineRoute
  AuthenticatedMyStyleGuideRoute: typeof AuthenticatedMyStyleGuideRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWardrobeRoute: typeof AuthenticatedWardrobeRoute
  AuthenticatedCheckoutTierRoute: typeof AuthenticatedCheckoutTierRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDnsCheckRoute: AuthenticatedDnsCheckRoute,
  AuthenticatedHouseholdRoute: AuthenticatedHouseholdRoute,
  AuthenticatedMagazineRoute: AuthenticatedMagazineRoute,
  AuthenticatedMyStyleGuideRoute: AuthenticatedMyStyleGuideRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWardrobeRoute: AuthenticatedWardrobeRoute,
  AuthenticatedCheckoutTierRoute: AuthenticatedCheckoutTierRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BiancaRoute: BiancaRoute,
  DnsMigrationRoute: DnsMigrationRoute,
  InquiryRoute: InquiryRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  TrustRoute: TrustRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiGenerateIllustrationRoute: ApiGenerateIllustrationRoute,
  StyleGuideColorRoute: StyleGuideColorRoute,
  StyleGuideComponentsRoute: StyleGuideComponentsRoute,
  StyleGuideIllustrationRoute: StyleGuideIllustrationRoute,
  StyleGuideLogoRoute: StyleGuideLogoRoute,
  StyleGuidePhotographyRoute: StyleGuidePhotographyRoute,
  StyleGuideTypographyRoute: StyleGuideTypographyRoute,
  StyleGuideVoiceRoute: StyleGuideVoiceRoute,
  StyleGuideIndexRoute: StyleGuideIndexRoute,
  ApiBeeMagazineStreamRoute: ApiBeeMagazineStreamRoute,
  ApiBeeStreamRoute: ApiBeeStreamRoute,
  ShareStyleGuideTokenRoute: ShareStyleGuideTokenRoute,
  ApiPublicBeeGuestRoute: ApiPublicBeeGuestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
