/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiBeeAppRouteImport } from './routes/api/bee/app'
import { Route as ApiBeeLooksRouteImport } from './routes/api/bee/looks'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingInquiryRouteImport } from './routes/api/billing/inquiry'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiBuzzConnectRouteImport } from './routes/api/buzz/connect'
import { Route as ApiBuzzConnectionsRouteImport } from './routes/api/buzz/connections'
import { Route as ApiBuzzFinishRouteImport } from './routes/api/buzz/finish'
import { Route as ApiBuzzPublishRouteImport } from './routes/api/buzz/publish'
import { Route as ApiCronBuzzRouteImport } from './routes/api/cron/buzz'
import { Route as ApiCronPushRouteImport } from './routes/api/cron/push'
import { Route as ApiHiveModerationRouteImport } from './routes/api/hive/moderation'
import { Route as ApiHoneyIndexRouteImport } from './routes/api/honey/index'
import { Route as ApiHoneyImportRouteImport } from './routes/api/honey/import'
import { Route as ApiOauthApproveRouteImport } from './routes/api/oauth/approve'
import { Route as ApiOauthClientRouteImport } from './routes/api/oauth/client'
import { Route as ApiOauthRegisterRouteImport } from './routes/api/oauth/register'
import { Route as ApiOauthRevokeRouteImport } from './routes/api/oauth/revoke'
import { Route as ApiOauthTokenRouteImport } from './routes/api/oauth/token'
import { Route as ApiPublicAppReturnRouteImport } from './routes/api/public/app-return'
import { Route as ApiPublicBeeSalesRouteImport } from './routes/api/public/bee-sales'
import { Route as ApiPublicVerifyRouteImport } from './routes/api/public/verify'
import { Route as ApiPushRecommendRouteImport } from './routes/api/push/recommend'
import { Route as ApiPushRegisterRouteImport } from './routes/api/push/register'
import { Route as ApiWardrobeAnalyzeRouteImport } from './routes/api/wardrobe/analyze'
import { Route as DotwellKnownOauthProtectedResourceApiMcpRouteImport } from './routes/[.]well-known/oauth-protected-resource/api/mcp'
import { Route as ApiPublicBuzzCallbackRouteImport } from './routes/api/public/buzz/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeAppRoute = ApiBeeAppRouteImport.update({
  id: '/api/bee/app',
  path: '/api/bee/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeeLooksRoute = ApiBeeLooksRouteImport.update({
  id: '/api/bee/looks',
  path: '/api/bee/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInquiryRoute = ApiBillingInquiryRouteImport.update({
  id: '/api/billing/inquiry',
  path: '/api/billing/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuzzConnectRoute = ApiBuzzConnectRouteImport.update({
  id: '/api/buzz/connect',
  path: '/api/buzz/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuzzConnectionsRoute = ApiBuzzConnectionsRouteImport.update({
  id: '/api/buzz/connections',
  path: '/api/buzz/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuzzFinishRoute = ApiBuzzFinishRouteImport.update({
  id: '/api/buzz/finish',
  path: '/api/buzz/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuzzPublishRoute = ApiBuzzPublishRouteImport.update({
  id: '/api/buzz/publish',
  path: '/api/buzz/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBuzzRoute = ApiCronBuzzRouteImport.update({
  id: '/api/cron/buzz',
  path: '/api/cron/buzz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPushRoute = ApiCronPushRouteImport.update({
  id: '/api/cron/push',
  path: '/api/cron/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHiveModerationRoute = ApiHiveModerationRouteImport.update({
  id: '/api/hive/moderation',
  path: '/api/hive/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHoneyIndexRoute = ApiHoneyIndexRouteImport.update({
  id: '/api/honey/',
  path: '/api/honey/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHoneyImportRoute = ApiHoneyImportRouteImport.update({
  id: '/api/honey/import',
  path: '/api/honey/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthApproveRoute = ApiOauthApproveRouteImport.update({
  id: '/api/oauth/approve',
  path: '/api/oauth/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthClientRoute = ApiOauthClientRouteImport.update({
  id: '/api/oauth/client',
  path: '/api/oauth/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthRegisterRoute = ApiOauthRegisterRouteImport.update({
  id: '/api/oauth/register',
  path: '/api/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthRevokeRoute = ApiOauthRevokeRouteImport.update({
  id: '/api/oauth/revoke',
  path: '/api/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthTokenRoute = ApiOauthTokenRouteImport.update({
  id: '/api/oauth/token',
  path: '/api/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppReturnRoute = ApiPublicAppReturnRouteImport.update({
  id: '/api/public/app-return',
  path: '/api/public/app-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeeSalesRoute = ApiPublicBeeSalesRouteImport.update({
  id: '/api/public/bee-sales',
  path: '/api/public/bee-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyRoute = ApiPublicVerifyRouteImport.update({
  id: '/api/public/verify',
  path: '/api/public/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRecommendRoute = ApiPushRecommendRouteImport.update({
  id: '/api/push/recommend',
  path: '/api/push/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRegisterRoute = ApiPushRegisterRouteImport.update({
  id: '/api/push/register',
  path: '/api/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWardrobeAnalyzeRoute = ApiWardrobeAnalyzeRouteImport.update({
  id: '/api/wardrobe/analyze',
  path: '/api/wardrobe/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceApiMcpRoute =
  DotwellKnownOauthProtectedResourceApiMcpRouteImport.update({
    id: '/api/mcp',
    path: '/api/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)
const ApiPublicBuzzCallbackRoute = ApiPublicBuzzCallbackRouteImport.update({
  id: '/api/public/buzz/callback',
  path: '/api/public/buzz/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/tryon': typeof ApiTryonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/looks': typeof ApiBeeLooksRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/inquiry': typeof ApiBillingInquiryRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/buzz/connect': typeof ApiBuzzConnectRoute
  '/api/buzz/connections': typeof ApiBuzzConnectionsRoute
  '/api/buzz/finish': typeof ApiBuzzFinishRoute
  '/api/buzz/publish': typeof ApiBuzzPublishRoute
  '/api/cron/buzz': typeof ApiCronBuzzRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/hive/moderation': typeof ApiHiveModerationRoute
  '/api/honey/import': typeof ApiHoneyImportRoute
  '/api/oauth/approve': typeof ApiOauthApproveRoute
  '/api/oauth/client': typeof ApiOauthClientRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/revoke': typeof ApiOauthRevokeRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
  '/api/public/app-return': typeof ApiPublicAppReturnRoute
  '/api/public/bee-sales': typeof ApiPublicBeeSalesRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/honey/': typeof ApiHoneyIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/public/buzz/callback': typeof ApiPublicBuzzCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/tryon': typeof ApiTryonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/looks': typeof ApiBeeLooksRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/inquiry': typeof ApiBillingInquiryRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/buzz/connect': typeof ApiBuzzConnectRoute
  '/api/buzz/connections': typeof ApiBuzzConnectionsRoute
  '/api/buzz/finish': typeof ApiBuzzFinishRoute
  '/api/buzz/publish': typeof ApiBuzzPublishRoute
  '/api/cron/buzz': typeof ApiCronBuzzRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/hive/moderation': typeof ApiHiveModerationRoute
  '/api/honey/import': typeof ApiHoneyImportRoute
  '/api/oauth/approve': typeof ApiOauthApproveRoute
  '/api/oauth/client': typeof ApiOauthClientRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/revoke': typeof ApiOauthRevokeRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
  '/api/public/app-return': typeof ApiPublicAppReturnRoute
  '/api/public/bee-sales': typeof ApiPublicBeeSalesRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/honey': typeof ApiHoneyIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/public/buzz/callback': typeof ApiPublicBuzzCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/privacy': typeof PrivacyRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/tryon': typeof ApiTryonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bee/app': typeof ApiBeeAppRoute
  '/api/bee/looks': typeof ApiBeeLooksRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/inquiry': typeof ApiBillingInquiryRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/buzz/connect': typeof ApiBuzzConnectRoute
  '/api/buzz/connections': typeof ApiBuzzConnectionsRoute
  '/api/buzz/finish': typeof ApiBuzzFinishRoute
  '/api/buzz/publish': typeof ApiBuzzPublishRoute
  '/api/cron/buzz': typeof ApiCronBuzzRoute
  '/api/cron/push': typeof ApiCronPushRoute
  '/api/hive/moderation': typeof ApiHiveModerationRoute
  '/api/honey/import': typeof ApiHoneyImportRoute
  '/api/oauth/approve': typeof ApiOauthApproveRoute
  '/api/oauth/client': typeof ApiOauthClientRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/revoke': typeof ApiOauthRevokeRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
  '/api/public/app-return': typeof ApiPublicAppReturnRoute
  '/api/public/bee-sales': typeof ApiPublicBeeSalesRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/api/push/recommend': typeof ApiPushRecommendRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/wardrobe/analyze': typeof ApiWardrobeAnalyzeRoute
  '/api/honey/': typeof ApiHoneyIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/public/buzz/callback': typeof ApiPublicBuzzCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/api/tryon'
    | '/oauth/authorize'
    | '/api/account/delete'
    | '/api/bee/app'
    | '/api/bee/looks'
    | '/api/billing/checkout'
    | '/api/billing/inquiry'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/buzz/connect'
    | '/api/buzz/connections'
    | '/api/buzz/finish'
    | '/api/buzz/publish'
    | '/api/cron/buzz'
    | '/api/cron/push'
    | '/api/hive/moderation'
    | '/api/honey/import'
    | '/api/oauth/approve'
    | '/api/oauth/client'
    | '/api/oauth/register'
    | '/api/oauth/revoke'
    | '/api/oauth/token'
    | '/api/public/app-return'
    | '/api/public/bee-sales'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/honey/'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/public/buzz/callback'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/privacy'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/api/tryon'
    | '/oauth/authorize'
    | '/api/account/delete'
    | '/api/bee/app'
    | '/api/bee/looks'
    | '/api/billing/checkout'
    | '/api/billing/inquiry'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/buzz/connect'
    | '/api/buzz/connections'
    | '/api/buzz/finish'
    | '/api/buzz/publish'
    | '/api/cron/buzz'
    | '/api/cron/push'
    | '/api/hive/moderation'
    | '/api/honey/import'
    | '/api/oauth/approve'
    | '/api/oauth/client'
    | '/api/oauth/register'
    | '/api/oauth/revoke'
    | '/api/oauth/token'
    | '/api/public/app-return'
    | '/api/public/bee-sales'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/honey'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/public/buzz/callback'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/api/tryon'
    | '/oauth/authorize'
    | '/api/account/delete'
    | '/api/bee/app'
    | '/api/bee/looks'
    | '/api/billing/checkout'
    | '/api/billing/inquiry'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/buzz/connect'
    | '/api/buzz/connections'
    | '/api/buzz/finish'
    | '/api/buzz/publish'
    | '/api/cron/buzz'
    | '/api/cron/push'
    | '/api/hive/moderation'
    | '/api/honey/import'
    | '/api/oauth/approve'
    | '/api/oauth/client'
    | '/api/oauth/register'
    | '/api/oauth/revoke'
    | '/api/oauth/token'
    | '/api/public/app-return'
    | '/api/public/bee-sales'
    | '/api/public/verify'
    | '/api/push/recommend'
    | '/api/push/register'
    | '/api/wardrobe/analyze'
    | '/api/honey/'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/public/buzz/callback'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PrivacyRoute: typeof PrivacyRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  ApiTryonRoute: typeof ApiTryonRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiBeeAppRoute: typeof ApiBeeAppRoute
  ApiBeeLooksRoute: typeof ApiBeeLooksRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingInquiryRoute: typeof ApiBillingInquiryRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiBuzzConnectRoute: typeof ApiBuzzConnectRoute
  ApiBuzzConnectionsRoute: typeof ApiBuzzConnectionsRoute
  ApiBuzzFinishRoute: typeof ApiBuzzFinishRoute
  ApiBuzzPublishRoute: typeof ApiBuzzPublishRoute
  ApiCronBuzzRoute: typeof ApiCronBuzzRoute
  ApiCronPushRoute: typeof ApiCronPushRoute
  ApiHiveModerationRoute: typeof ApiHiveModerationRoute
  ApiHoneyImportRoute: typeof ApiHoneyImportRoute
  ApiOauthApproveRoute: typeof ApiOauthApproveRoute
  ApiOauthClientRoute: typeof ApiOauthClientRoute
  ApiOauthRegisterRoute: typeof ApiOauthRegisterRoute
  ApiOauthRevokeRoute: typeof ApiOauthRevokeRoute
  ApiOauthTokenRoute: typeof ApiOauthTokenRoute
  ApiPublicAppReturnRoute: typeof ApiPublicAppReturnRoute
  ApiPublicBeeSalesRoute: typeof ApiPublicBeeSalesRoute
  ApiPublicVerifyRoute: typeof ApiPublicVerifyRoute
  ApiPushRecommendRoute: typeof ApiPushRecommendRoute
  ApiPushRegisterRoute: typeof ApiPushRegisterRoute
  ApiWardrobeAnalyzeRoute: typeof ApiWardrobeAnalyzeRoute
  ApiHoneyIndexRoute: typeof ApiHoneyIndexRoute
  ApiPublicBuzzCallbackRoute: typeof ApiPublicBuzzCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/app': {
      id: '/api/bee/app'
      path: '/api/bee/app'
      fullPath: '/api/bee/app'
      preLoaderRoute: typeof ApiBeeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bee/looks': {
      id: '/api/bee/looks'
      path: '/api/bee/looks'
      fullPath: '/api/bee/looks'
      preLoaderRoute: typeof ApiBeeLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/inquiry': {
      id: '/api/billing/inquiry'
      path: '/api/billing/inquiry'
      fullPath: '/api/billing/inquiry'
      preLoaderRoute: typeof ApiBillingInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buzz/connect': {
      id: '/api/buzz/connect'
      path: '/api/buzz/connect'
      fullPath: '/api/buzz/connect'
      preLoaderRoute: typeof ApiBuzzConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buzz/connections': {
      id: '/api/buzz/connections'
      path: '/api/buzz/connections'
      fullPath: '/api/buzz/connections'
      preLoaderRoute: typeof ApiBuzzConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buzz/finish': {
      id: '/api/buzz/finish'
      path: '/api/buzz/finish'
      fullPath: '/api/buzz/finish'
      preLoaderRoute: typeof ApiBuzzFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buzz/publish': {
      id: '/api/buzz/publish'
      path: '/api/buzz/publish'
      fullPath: '/api/buzz/publish'
      preLoaderRoute: typeof ApiBuzzPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/buzz': {
      id: '/api/cron/buzz'
      path: '/api/cron/buzz'
      fullPath: '/api/cron/buzz'
      preLoaderRoute: typeof ApiCronBuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/push': {
      id: '/api/cron/push'
      path: '/api/cron/push'
      fullPath: '/api/cron/push'
      preLoaderRoute: typeof ApiCronPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hive/moderation': {
      id: '/api/hive/moderation'
      path: '/api/hive/moderation'
      fullPath: '/api/hive/moderation'
      preLoaderRoute: typeof ApiHiveModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/honey/': {
      id: '/api/honey/'
      path: '/api/honey'
      fullPath: '/api/honey/'
      preLoaderRoute: typeof ApiHoneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/honey/import': {
      id: '/api/honey/import'
      path: '/api/honey/import'
      fullPath: '/api/honey/import'
      preLoaderRoute: typeof ApiHoneyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/approve': {
      id: '/api/oauth/approve'
      path: '/api/oauth/approve'
      fullPath: '/api/oauth/approve'
      preLoaderRoute: typeof ApiOauthApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/client': {
      id: '/api/oauth/client'
      path: '/api/oauth/client'
      fullPath: '/api/oauth/client'
      preLoaderRoute: typeof ApiOauthClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/register': {
      id: '/api/oauth/register'
      path: '/api/oauth/register'
      fullPath: '/api/oauth/register'
      preLoaderRoute: typeof ApiOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/revoke': {
      id: '/api/oauth/revoke'
      path: '/api/oauth/revoke'
      fullPath: '/api/oauth/revoke'
      preLoaderRoute: typeof ApiOauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/token': {
      id: '/api/oauth/token'
      path: '/api/oauth/token'
      fullPath: '/api/oauth/token'
      preLoaderRoute: typeof ApiOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-return': {
      id: '/api/public/app-return'
      path: '/api/public/app-return'
      fullPath: '/api/public/app-return'
      preLoaderRoute: typeof ApiPublicAppReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bee-sales': {
      id: '/api/public/bee-sales'
      path: '/api/public/bee-sales'
      fullPath: '/api/public/bee-sales'
      preLoaderRoute: typeof ApiPublicBeeSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify': {
      id: '/api/public/verify'
      path: '/api/public/verify'
      fullPath: '/api/public/verify'
      preLoaderRoute: typeof ApiPublicVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/recommend': {
      id: '/api/push/recommend'
      path: '/api/push/recommend'
      fullPath: '/api/push/recommend'
      preLoaderRoute: typeof ApiPushRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/register': {
      id: '/api/push/register'
      path: '/api/push/register'
      fullPath: '/api/push/register'
      preLoaderRoute: typeof ApiPushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wardrobe/analyze': {
      id: '/api/wardrobe/analyze'
      path: '/api/wardrobe/analyze'
      fullPath: '/api/wardrobe/analyze'
      preLoaderRoute: typeof ApiWardrobeAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/api/mcp': {
      id: '/.well-known/oauth-protected-resource/api/mcp'
      path: '/api/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
    '/api/public/buzz/callback': {
      id: '/api/public/buzz/callback'
      path: '/api/public/buzz/callback'
      fullPath: '/api/public/buzz/callback'
      preLoaderRoute: typeof ApiPublicBuzzCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceApiMcpRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceApiMcpRoute:
      DotwellKnownOauthProtectedResourceApiMcpRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PrivacyRoute: PrivacyRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  ApiTryonRoute: ApiTryonRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiBeeAppRoute: ApiBeeAppRoute,
  ApiBeeLooksRoute: ApiBeeLooksRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingInquiryRoute: ApiBillingInquiryRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiBuzzConnectRoute: ApiBuzzConnectRoute,
  ApiBuzzConnectionsRoute: ApiBuzzConnectionsRoute,
  ApiBuzzFinishRoute: ApiBuzzFinishRoute,
  ApiBuzzPublishRoute: ApiBuzzPublishRoute,
  ApiCronBuzzRoute: ApiCronBuzzRoute,
  ApiCronPushRoute: ApiCronPushRoute,
  ApiHiveModerationRoute: ApiHiveModerationRoute,
  ApiHoneyImportRoute: ApiHoneyImportRoute,
  ApiOauthApproveRoute: ApiOauthApproveRoute,
  ApiOauthClientRoute: ApiOauthClientRoute,
  ApiOauthRegisterRoute: ApiOauthRegisterRoute,
  ApiOauthRevokeRoute: ApiOauthRevokeRoute,
  ApiOauthTokenRoute: ApiOauthTokenRoute,
  ApiPublicAppReturnRoute: ApiPublicAppReturnRoute,
  ApiPublicBeeSalesRoute: ApiPublicBeeSalesRoute,
  ApiPublicVerifyRoute: ApiPublicVerifyRoute,
  ApiPushRecommendRoute: ApiPushRecommendRoute,
  ApiPushRegisterRoute: ApiPushRegisterRoute,
  ApiWardrobeAnalyzeRoute: ApiWardrobeAnalyzeRoute,
  ApiHoneyIndexRoute: ApiHoneyIndexRoute,
  ApiPublicBuzzCallbackRoute: ApiPublicBuzzCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
